INSERT INTO courses (course_name, description, code, degree_id, teacher_id, created_at, updated_at) VALUES
('Data Structures', 'Learn fundamental data structures and algorithms', 'CS201', 1, 8, NOW(), NOW()),
('Database Management Systems', 'Advanced database design and SQL', 'CS301', 1, 8, NOW(), NOW()),
('Web Development', 'Frontend and backend web development', 'CS205', 1, 8, NOW(), NOW()),
('Business Management', 'Principles of business management', 'BUS101', 2, 8, NOW(), NOW()),
('Economics 101', 'Introduction to microeconomics', 'BUS102', 2, 8, NOW(), NOW()),
('Financial Accounting', 'Basic accounting principles', 'BUS201', 2, 8, NOW(), NOW()),
('Physics I', 'Mechanics and thermodynamics', 'ENG101', 3, 8, NOW(), NOW()),
('Engineering Mathematics', 'Advanced calculus for engineers', 'ENG102', 3, 8, NOW(), NOW()),
('Materials Science', 'Properties and applications of materials', 'ENG203', 3, 8, NOW(), NOW()),
('Entrepreneurship', 'Starting and managing businesses', 'BAS101', 4, 8, NOW(), NOW()),
('Operations Management', 'Managing business operations', 'BAS201', 4, 8, NOW(), NOW()),
('Strategic Management', 'Corporate strategy development', 'BAS301', 4, 8, NOW(), NOW()),
('Network Administration', 'Managing computer networks', 'IT101', 5, 8, NOW(), NOW()),
('Cloud Computing', 'Cloud platforms and services', 'IT202', 5, 8, NOW(), NOW()),
('Cybersecurity', 'Information security principles', 'IT303', 5, 8, NOW(), NOW()),
('Shakespeare Studies', 'Works of William Shakespeare', 'ENG301', 6, 8, NOW(), NOW()),
('Modern Poetry', 'Contemporary poetry analysis', 'ENG302', 6, 8, NOW(), NOW()),
('Literary Criticism', 'Theory and practice of literary analysis', 'ENG401', 6, 8, NOW(), NOW()),
('Structural Analysis', 'Analysis of structures', 'CE201', 7, 8, NOW(), NOW()),
('Surveying and Mapping', 'Land surveying techniques', 'CE202', 7, 8, NOW(), NOW()),
('Construction Management', 'Project management in construction', 'CE303', 7, 8, NOW(), NOW()),
('Anatomy and Physiology', 'Human body systems', 'NURS101', 8, 8, NOW(), NOW()),
('Pharmacology', 'Study of drugs and medications', 'NURS201', 8, 8, NOW(), NOW()),
('Clinical Practice', 'Hands-on nursing skills', 'NURS301', 8, 8, NOW(), NOW()),
('Molecular Biology', 'DNA and protein synthesis', 'BIO201', 9, 8, NOW(), NOW()),
('Genetic Engineering', 'Gene manipulation techniques', 'BIO301', 9, 8, NOW(), NOW()),
('Bioinformatics', 'Computational biology', 'BIO302', 9, 8, NOW(), NOW()),
('Auditing', 'Principles of internal and external auditing', 'ACC201', 10, 8, NOW(), NOW()),
('Tax Planning', 'Individual and corporate taxation', 'ACC301', 10, 8, NOW(), NOW()),
('Financial Analysis', 'Analysis of financial statements', 'ACC202', 10, 8, NOW(), NOW()),
('World War History', 'Study of World Wars', 'HIST201', 11, 8, NOW(), NOW()),
('Ancient Civilizations', 'Ancient Egypt, Greece, Rome', 'HIST101', 11, 8, NOW(), NOW()),
('Modern History', 'History from 1800 to present', 'HIST301', 11, 8, NOW(), NOW());
